apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  values:
    domainFilters:
      - owega.infra-coders.com
    zoneIdFilters:
      - Z01542683PEN3FQE8Q164
